### ISSUE TITLE
Page format adjustment

### ISSUE THREAD

**Issue by ryan8614** [ryan8614/5505-Project#10]
<img width="1650" alt="Marketplace" src="https://github.com/ryan8614/5505-Project/assets/156677666/7d11d62e-2803-4958-97af-457cc1e0ee1c">

The format of this part of the content needs further adjustment

**Comment by Shaohongzheng** [comment]
Can the text content part be deleted a little bit? It seems that the content is very complicated and is not conducive to the streamlined display of the page.

**Comment by JasAAA** [comment]
Someone modified the main.css file leads to the style conflicts to this page.I will push the last version css to reset it.
