### ISSUE TITLE
Adding a new Error Modal box when there are no more fragments

### ISSUE THREAD

**Issue by Shaohongzheng** [ryan8614/5505-Project#11]
]
<img width="768" alt="Screenshot 2024-05-10 at 10 35 24 pm" src="https://github.com/ryan8614/5505-Project/assets/167878877/09ad294f-3d8c-44b4-8635-4841c61136ab">
I found out that we only have the Modal Box before for only when users successfully click the 'try your luck' button. However, if there are no more fragments, the given error message seems to be extremely blunt and not user-friendly. So I add a new Modal Box only for error situation and also made some modifications to raffle.js file.  And now the effect looks much better now. 
<img width="499" alt="Screenshot 2024-05-10 at 10 43 30 pm" src="https://github.com/ryan8614/5505-Project/assets/167878877/e1f6e57f-0ac9-42af-a0bc-e25b8d3f4ec6">

**Comment by JasAAA** [comment]
good job!
