### ISSUE TITLE
css style of dashboard.html

### ISSUE THREAD

**Issue by ryan8614** [ryan8614/5505-Project#14]
<img width="1675" alt="截屏2024-05-11 10 58 02" src="https://github.com/ryan8614/5505-Project/assets/156677666/57e7deb4-8d15-4c03-b0a7-761224810980">
There are still some problems with the css format here, and the dynamic effects of the lottery need to be updated.

**Comment by JasAAA** [comment]
the stye works well on my laptop.it displays like that in certain screen width or always like that?Have you revert to the last version CSS?some modify on main.css affects the dashboard style.By the way,I already update spin.js to fix the dynamix effects problem.

**Comment by JasAAA** [comment]
yeah,it's all good now.
