### ISSUE TITLE
move lottery modal to spin button

### ISSUE THREAD

**Issue by JasAAA** [ryan8614/5505-Project#3]
I add a spin wheel to lottery section with a spin button.The raffle modal need to be transfer to spin button,there might be some conflicts to do so.

**Comment by ryan8614** [comment]
I will try to use js or css to adjust your dynamic effects to resolve the conflict, I will solve this problem tomorrow

**Comment by Shaohongzheng** [comment]
Maybe for the basic lottery part, the spin wheel animation should be happened after users click the "Try your luck". I will try to fix this thing. Cheers
