### ISSUE TITLE
Log out function is not working anymore?

### ISSUE THREAD

**Issue by JasAAA** [ryan8614/5505-Project#4]
Hey guys,the log out function seems like not working now.Any idea?

**Comment by ryan8614** [comment]
I have modified the relevant code, it doesn't work because Bootstrap version does not match the code, data-toggle and data-target should be replaced by data-bs-toggle and data-bs-target

**Comment by Shaohongzheng** [comment]
I remembered I do some modification on the logout module several days ago and it did work. And now it seems work as well.
