### ISSUE TITLE
Format conflicts and priorities

### ISSUE THREAD

**Issue by yifei-T** [ryan8614/5505-Project#6]
When I use a container, due to the default format of bootstrap, the background of the container is white. When I add a new class to cover it, it seems that I cannot cover it and make it transparent.

**Comment by JasAAA** [comment]
We can change the background color of bootstrap us 'bg',but if you want to make the background transparent,probally need to use CSS.Just give it a try.If not working,let's figure out together then.

**Comment by yifei-T** [comment]
Got it, I set the new ID in CSS style to overwrite its priority, Cheers.
