### ISSUE TITLE
element alignment issues in dashboard

### ISSUE THREAD

**Issue by yifei-T** [ryan8614/5505-Project#7]
I have tried various ways to adapt to different screen sizes, like using Bootstrap classes such as sm, md and lg, and adding new class, but I can't seem to put the elements on the page side by side. Is there some conflicts?

**Comment by JasAAA** [comment]
The webpage works well on 14 inch screen and below,so I didn't realize this issue before,but I'll also have a look when I have time.

**Comment by JasAAA** [comment]
Maybe try to add sm md lg class to meet all kinds of device needs.Take this website as a refernce:https://www.w3schools.com/bootstrap/bootstrap_grid_large.asp 
Check whether it helps.
